edition = "2021"

imports_granularity = "Item"
group_imports = "StdExternalCrate"
reorder_imports = true

max_width = 100
use_small_heuristics = "Default"
chain_width = 80
single_line_if_else_max_width = 80


struct_lit_width = 40
struct_variant_width = 40
enum_discrim_align_threshold = 40
fn_params_layout = "Tall"
fn_call_width = 80

empty_item_single_line = false
brace_style = "SameLineWhere"

wrap_comments = false
comment_width = 100

reorder_impl_items = false
merge_derives = true

newline_style = "Unix"
tab_spaces = 4
